title: Linux Course
description: Complete Linux administration course
theme: jekyll-theme-cayman

# Configuration pour les chemins relatifs
baseurl: ""
url: "https://N0vachr0n0.github.io"

# Param√®tres markdown
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true
  extensions:
    - autolink

# Exclure certains fichiers
exclude:
  - README.md
  - README-ENG.md
